"use client";

import * as THREE from "three";

type Opts = {
  width?: number;
  height?: number;
  paper?: string;
  accent?: string;
  brand?: string;
  brandLao?: string;
  code?: string;
  subtitle?: string;
  torn?: boolean;
};

const LATIN_DISPLAY = "'Space Grotesk', 'Inter', sans-serif";
// Use Noto Serif Lao for display weight Lao text. Falls back to system Lao font if not yet loaded.
const LAO_DISPLAY =
  "'Noto Serif Lao', 'Phetsarath OT', 'Saysettha OT', 'Lao UI', system-ui, sans-serif";
const MONO = "'JetBrains Mono', ui-monospace, monospace";

// Kick off Lao font loading once on the client so canvas labels can render with
// the proper face. The texture will be regenerated by makeLabelTexture's callers
// (via the `nonce` argument) when the fonts finish loading.
let _laoFontsReady = false;
let _laoFontsPromise: Promise<void> | null = null;
const _readyListeners = new Set<() => void>();

function ensureLaoFonts(): void {
  if (typeof document === "undefined" || _laoFontsReady) return;
  if (_laoFontsPromise) return;
  if (!("fonts" in document)) {
    _laoFontsReady = true;
    return;
  }
  _laoFontsPromise = Promise.all([
    document.fonts.load(`700 86px 'Noto Serif Lao'`),
    document.fonts.load(`500 36px 'Noto Sans Lao'`),
  ])
    .then(() => {
      _laoFontsReady = true;
      _readyListeners.forEach((fn) => fn());
      _readyListeners.clear();
    })
    .catch(() => {
      _laoFontsReady = true;
    }) as unknown as Promise<void>;
}

export function onLaoFontsReady(fn: () => void) {
  if (typeof document === "undefined") return () => {};
  ensureLaoFonts();
  if (_laoFontsReady) {
    fn();
    return () => {};
  }
  _readyListeners.add(fn);
  return () => _readyListeners.delete(fn);
}

export function laoFontsReady() {
  return _laoFontsReady;
}

export function makeLabelTexture(opts: Opts = {}) {
  if (typeof document === "undefined") {
    return null as unknown as THREE.CanvasTexture;
  }
  ensureLaoFonts();

  const {
    width = 1024,
    height = 360,
    paper = "#fbf5e6",
    accent = "#0d5b2e",
    brand = "kittivong",
    brandLao = "ກິດຕິວົງ",
    code = "VTE-26",
    subtitle = "PHARMACY · TINCTURE · 30 ML",
    torn = true,
  } = opts;

  const c = document.createElement("canvas");
  c.width = width;
  c.height = height;
  const ctx = c.getContext("2d")!;

  ctx.clearRect(0, 0, width, height);

  const topY = torn ? 24 : 0;
  const bottomY = torn ? height - 24 : height;

  ctx.fillStyle = paper;
  if (torn) {
    ctx.beginPath();
    ctx.moveTo(0, topY);
    for (let x = 0; x <= width; x += 16) {
      const y = topY + (Math.sin(x * 0.07) + Math.sin(x * 0.21 + 1)) * 1.4;
      ctx.lineTo(x, y);
    }
    ctx.lineTo(width, bottomY);
    for (let x = width; x >= 0; x -= 16) {
      const y = bottomY + (Math.sin(x * 0.08 + 2) + Math.sin(x * 0.19)) * 1.4;
      ctx.lineTo(x, y);
    }
    ctx.closePath();
    ctx.fill();
  } else {
    ctx.fillRect(0, 0, width, height);
  }

  ctx.fillStyle = accent;
  ctx.fillRect(60, topY + 30, width - 120, 3);
  ctx.fillRect(60, bottomY - 32, width - 120, 3);
  ctx.fillRect(60, topY + 38, width - 120, 1);
  ctx.fillRect(60, bottomY - 24, width - 120, 1);

  drawCrest(ctx, width / 2, topY + 100, accent);

  ctx.fillStyle = "#1a1a1a";
  ctx.font = `700 86px ${LATIN_DISPLAY}`;
  ctx.textAlign = "center";
  ctx.textBaseline = "middle";
  ctx.fillText(brand, width / 2, topY + 180);

  // Lao brand line uses a formal Lao face.
  ctx.fillStyle = accent;
  ctx.font = `600 40px ${LAO_DISPLAY}`;
  ctx.fillText(brandLao, width / 2, topY + 232);

  ctx.fillStyle = "#3b3b3b";
  ctx.font = `500 22px ${MONO}`;
  ctx.fillText(subtitle, width / 2, topY + 272);

  ctx.fillStyle = accent;
  ctx.font = `500 22px ${MONO}`;
  ctx.textAlign = "left";
  ctx.fillText(code, 80, topY + 60);
  ctx.textAlign = "right";
  ctx.fillText("ESTD 2026", width - 80, topY + 60);

  ctx.textAlign = "center";
  ctx.fillStyle = "#666";
  ctx.font = `400 16px ${MONO}`;
  ctx.fillText("VIENTIANE · LAO PDR", width / 2, bottomY - 50);

  const tex = new THREE.CanvasTexture(c);
  tex.colorSpace = THREE.SRGBColorSpace;
  tex.anisotropy = 8;
  tex.needsUpdate = true;
  return tex;
}

function drawCrest(
  ctx: CanvasRenderingContext2D,
  cx: number,
  cy: number,
  color: string
) {
  ctx.save();
  ctx.strokeStyle = color;
  ctx.fillStyle = color;
  ctx.lineWidth = 2.4;
  ctx.lineCap = "round";
  ctx.lineJoin = "round";

  ctx.beginPath();
  ctx.moveTo(cx - 40, cy + 6);
  ctx.quadraticCurveTo(cx - 24, cy - 18, cx - 6, cy);
  ctx.quadraticCurveTo(cx - 24, cy + 16, cx - 40, cy + 6);
  ctx.fill();

  ctx.beginPath();
  ctx.moveTo(cx + 40, cy + 6);
  ctx.quadraticCurveTo(cx + 24, cy - 18, cx + 6, cy);
  ctx.quadraticCurveTo(cx + 24, cy + 16, cx + 40, cy + 6);
  ctx.fill();

  ctx.beginPath();
  ctx.moveTo(cx - 18, cy + 4);
  ctx.lineTo(cx + 18, cy + 4);
  ctx.lineTo(cx + 12, cy + 16);
  ctx.lineTo(cx - 12, cy + 16);
  ctx.closePath();
  ctx.stroke();

  ctx.beginPath();
  ctx.moveTo(cx - 2, cy + 8);
  ctx.lineTo(cx + 10, cy - 8);
  ctx.stroke();

  ctx.restore();
}
